/* eslint-disable import/no-extraneous-dependencies */
const gulp = require('gulp')
const sourcemaps = require('gulp-sourcemaps')
const gzip = require('gulp-gzip')
const minify = require('gulp-minify')
const named = require('vinyl-named')
const webpackStream = require('webpack-stream')
const devConfig = require('../webpack/dev')
const prodConfig = require('../webpack/prod')
const prodServerConfig = require('../webpack/prod/server')


gulp.task('webpack:prod', () => gulp.src('client/index.js')
    .pipe(named())
    .pipe(webpackStream(prodConfig))
    .pipe(minify())
    .pipe(gzip())
    .pipe(gulp.dest('dist'))
)

gulp.task('webpack:prod:server', () => gulp.src('client/server.js')
    .pipe(named())
    .pipe(webpackStream(prodServerConfig))
    .pipe(minify())
    .pipe(gulp.dest('dist'))
)

gulp.task('webpack:dev', () => gulp.src('client/index.js')
    .pipe(named())
    .pipe(webpackStream(devConfig))
    .pipe(sourcemaps.init())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'))
)
