
import { toConstant } from '../utils'

const ACTIONS = `
SET_CANVAS
CHANGE_CANVAS_STYLE
ADD_TO_CANVAS
REMOVE_FROM_CANVAS
CLONE_FROM_CANVAS
CHANGE_COMPONENT_CONFIG
FOCUS_ON_CANVAS_COMPONENT
`

export default toConstant(ACTIONS)
